---
template:
  fieldlabel:
    elementName: label
    body: 'Default textfield:'
    attributes:
    - - class
      - '"ocl-input-label"'
  elementName: input
  attributes:
  - - class
    - '"ocl-input"'
  - - placeholder
    - '"Default text field"'
  - - type
    - '"text"'
  fielderror:
    elementName: span
    body: 'Default error massage'
    attributes:
    - - class
      - '"ocl-input-error"'
state: {}
