---
template:
  elementName: div
  attributes:
  - - class
    - '"ocl-drawer-nav"'
  primaryLink:
  -
    icon: <i class="fa fa-home" aria-hidden="true"></i>
    text: Dashboard
  -
    icon: <i class="fa fa-graduation-cap" aria-hidden="true"></i>
    text: StudentLink
  -
    icon: <i class="fa fa-bookmark" aria-hidden="true"></i>
    text: My List
  -
    icon: <i class="fa fa-hand-lizard-o icon-rotated" aria-hidden="true"></i>
    text: Skill Library
  -
    icon: <i class="fa fa-book" aria-hidden="true"></i>
    text: Repertoire Library
  secondaryLink:
    -
      text: Tour
    -
      text: News
    -
      text: Help
state: {}
