---
template:
 elementName: div
 attributes:
 - - class
   - '"ocl-watch-event"'
 img:
    elementName: img
    attributes:
    - - class
      - '"ocl-watch-event__image"'
    - - src
      - '"http://placehold.it/188x106"'
 title:
    elementName: a
    attributes:
    - - class
      - '"ocl-watch-event__title"'
    - - href
      - '"#"'
    body: 'One-Octave Arpeggios: Overview, Part 5'
 subtitle:
    elementName: a
    attributes:
    - - class
      - '"ocl-watch-event__subtitle"'
    - - href
      - '"#"'
    body: '3-Dimensional Movement'
 detail:
    elementName: span
    attributes:
    - - class
      - '"ocl-watch-event__detail"'
    body: 'Watched for 56 seconds'
state: {}
