---
template:
  elementName: div
  attributes:
  - - class
    - '"ocl-t-modal-page"'
  textfields:
    elementName: form
    email:
      fieldlabel:
        elementName: label
        body: 'Email:'
        attributes:
        - - class
          - '"ocl-input-label"'
      elementName: input
      attributes:
      - - class
        - '"ocl-input"'
      - - placeholder
        - '"enter your email address"'
      - - type
        - '"email"'
      fielderror:
        elementName: span
        body: Wrong e-mail
        attributes:
        - - class
          - '"ocl-input-error ocl-input--display-none"'
    password:
      fieldlabel:
        elementName: label
        body: 'Password:'
        attributes:
        - - class
          - '"ocl-input-label"'
      elementName: input
      attributes:
      - - class
        - '"ocl-input"'
      - - placeholder
        - '"enter your password"'
      - - type
        - "'password'"
      fielderror:
        elementName: span
        body: Wrong password
        attributes:
        - - class
          - '"ocl-input-error ocl-input--display-none"'
  button:
    elementName: button
    body: <span class="ocl-button__label">Sign in</span>
    attributes:
    - - class
      - '"ocl-button ocl-button__signin ocl-button--centered"'

state: {}
