---
template:
  elementName: div
  attributes:
  - - class
    - '"ocl-student-link-filter"'
  active:
    elementName: label
    attributes:
    - - class
      - '"ocl-filter-toggle"'
    input:
      elementName: input
      attributes:
      - - type
        - '"radio"'
      - - class
        - '"ocl-filter-toggle__input"'
      - - name
        - '"group"'
      - - value
        - '"toggle"'
      body: '<span class="ocl-filter-toggle__text">Recently Active</span>'
  alpha:
    elementName: label
    attributes:
    - - class
      - '"ocl-filter-toggle"'
    input:
      elementName: input
      attributes:
      - - type
        - '"radio"'
      - - class
        - '"ocl-filter-toggle__input"'
      - - name
        - '"group"'
      - - value
        - '"toggle"'
      body: '<span class="ocl-filter-toggle__text">Alphabetical</span>'
  date:
    elementName: label
    attributes:
    - - class
      - '"ocl-filter-toggle"'
    input:
      elementName: input
      attributes:
      - - type
        - '"radio"'
      - - class
        - '"ocl-filter-toggle__input"'
      - - name
        - '"group"'
      - - value
        - '"toggle"'
      body: '<span class="ocl-filter-toggle__text">Date Added</span>'
  status:
    elementName: label
    attributes:
    - - class
      - '"ocl-filter-toggle"'
    input:
      elementName: input
      attributes:
      - - type
        - '"radio"'
      - - class
        - '"ocl-filter-toggle__input"'
      - - name
        - '"group"'
      - - value
        - '"toggle"'
      body: '<span class="ocl-filter-toggle__text">Status</span>'
state: {}
