---
template:
  elementName: div
  attributes:
  - - class
    - '"ocl-account-menu"'
  toggle:
    elementName: div
    attributes:
    - - class
      - '"ocl-account-menu__toggle"'
    username:
      elementName: div
      body: <span>USERNAME</span>
      attributes:
      - - class
        - '"ocl-account-menu__username"'
    icon:
      elementName: div
      attributes:
      - - class
        - '"ocl-account-menu__user-icon"'
      body: <span>U</span>
  popover:
    elementName: div
    attributes:
      - - class
        - '"ocl-popover"'
    list:
      elementName: div
      attributes:
      - - class
        - '"ocl-popover__list"'
    close:
      elementName: button
      body: <div class="ocl-popover__close-element"></div>
      attributes:
      - - class
        - '"ocl-popover__close"'
    link:
      elementName: a
      body: <span>Link in pop</span>
      attributes:
      - - class
        - '"ocl-popover__link"'
      - - href
        - '"#"'
state: {}
