---
template:
  elementName: div
  attributes:
  - - class
    - '"ocl-tabs"'
  controls:
    elementName: div
    attributes:
    - - class
      - '"ocl-tabs__controls"'
    tab-1:
      elementName: label
      attributes:
      - - class
        - '"ocl-tabs__label"'
      content:
        elementName: div
        attributes:
        - - class
          - '"ocl-tabs__label-content"'
        body: 'Assignments'
      input:
        elementName: input
        attributes:
        - checked
        - - type
          - '"radio"'
        - - class
          - '"ocl-tabs__input"'
        - - name
          - '"tab-input-name"'
        - - data-tab-control-name
          - '"tab-1"'
    tab-2:
      elementName: label
      attributes:
      - - class
        - '"ocl-tabs__label"'
      content:
        elementName: div
        attributes:
        - - class
          - '"ocl-tabs__label-content"'
        body: 'Skill Profile'
      input:
        elementName: input
        attributes:
        - - type
          - '"radio"'
        - - class
          - '"ocl-tabs__input"'
        - - name
          - '"tab-input-name"'
        - - data-tab-control-name
          - '"tab-2"'
  panels:
    elementName: div
    attributes:
    - - class
      - '"ocl-tabs__panels"'
    tab-1:
      elementName: div
      attributes:
      - - class
        - '"ocl-tabs__panel ocl-tabs__panel--selected"'
      - - data-tab-control-name
        - '"tab-1"'
      body: 'Tab 1 content'
    tab-2:
      elementName: div
      attributes:
      - - class
        - '"ocl-tabs__panel"'
      - - data-tab-control-name
        - '"tab-2"'
      body: 'Tab 2 content'
state: {}
