---
template:
  elementName: div
  attributes:
  - - class
    - '"ocl-page-title"'
  heading:
    elementName: h1
    attributes:
    - - class
      - '"ocl-page-title__heading"'
    body: Page title
state: {}
