"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("@angular/animations");
require("@angular/common");
require("@angular/compiler");
require("@angular/core");
require("@angular/forms");
require("@angular/http");
require("@angular/platform-browser");
require("@angular/platform-browser-dynamic");
require("@angular/router");
require("redux");
require("redux-logger");
require("redux-observable");
require("@angular-redux/store");
require("@angular-redux/form");
require("@angular-redux/router");
require("immutable");
require("rxjs");
//# sourceMappingURL=vendor.js.map