---
template:
  elementName: span
  attributes:
  - - class
    - '"ocl-search"'
  input:
    elementName: input
    attributes:
    - - class
      - '"ocl-search__input"'
    - - placeholder
      - '"Search"'
  button:
    elementName: button
    body: <i class="fa fa-search" aria-hidden="true"></i>
    attributes:
    - - class
      - '"ocl-search__button"'
state: {}
